<h1>Add a Meetups</h1>

<?php
    $form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($form->get('title')) ?>

<?= $this->formRow($form->get('description')) ?>

<?= $this->formRow($form->get('dateStart')) ?>

<?= $this->formRow($form->get('dateEnd')) ?>

<?= $this->formInput($form->get('submit')) ?>

<?= $this->form()->closeTag($form); ?>
