<h1>List Meetups</h1>

<div class="list-group">

<?php if(isset($this->meetups)): ?>
    <?php foreach ($this->meetups as $meetup):  ?>

    <div>	
  <a href="<?= $this->url('display', ['id' => $meetup->getId()]); ?>" class="list-group-item">
  	<h4 class="list-group-item-heading"><?= $meetup->getTitle() ?>  | <?= $meetup->getDateStart()->format('j/m/y'); ?> - <?= $meetup->getDateEnd()->format('j/m/y'); ?></h4>
      <p class="list-group-item-text"> <?= $meetup->getDescription() ?> </p>
  	   <!--<a href="<?= $this->url('meetup/add'); ?>" class="btn btn-primary">Edit</a>
  	<a href="<?= $this->url('meetup/add'); ?>" class="btn btn-primary">Delete</a> -->  </a>
  	
  
</div>
    
    <?php endforeach; ?>
	<?php endif; ?>

<?php if(!isset($this->meetups)): ?>
		<div class="alert alert-warning">
  <strong>Attention !</strong> Votre liste de meetup est vide ! Appuyer sur le bouton "Add new meetup"pour créer votre premier Meetup.
		</div>
<?php endif; ?>	


</div>

<a href="<?= $this->url('meetup/add'); ?>" class="btn btn-primary">Add new Meetup</a>
