<h1>List Meetups</h1>

<div class="list-group">

    <?php foreach ($this->meetups as $meetup):  ?>
    	
  <a href="/#" class="list-group-item"><?= $meetup->getTitle() ?> | <?= $meetup->getDateStart()->format('j/m/y'); ?> - <?= $meetup->getDateEnd()->format('j/m/y'); ?></a>
  

    
    <?php endforeach; ?>
</div>

<a href="<?= $this->url('meetup/add'); ?>" class="btn btn-primary">Add new Meetup</a>
