<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Meetup List Application</span></h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">ZF Skeleton Application</a>.
        You are currently running Zend Framework version <?= \Application\Module::VERSION ?>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on ZF.
    </p>

    <p><a class="btn btn-success btn-lg" href="<?= $this->url('meetup'); ?>">Accéder au listing des Meetups</a></p>
</div>


